import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
         <header className="p-4 bg-yellow-500 text-white text-center">
                <h1>This is header</h1>
          </header>    

        {children}

          <footer className="p-4 bg-gray-800 text-white text-center mt-8">
                <p>&copy; 2024 My Next.js App. All rights reserved.</p>
          </footer>
      </body>
    </html>
  );
}
